### ISSUE TITLE
Add an option to create menu in the QGIS browser

### ISSUE THREAD

**Issue by jmkerloch** [aeag/MenuFromProject-Qgis-Plugin#107]
### Feature description

In addition to the possibility of adding a menu in the QGIS menu bar and in the "Add a layer menu", we propose to add a new location in the project's settings.

![image](https://github.com/user-attachments/assets/4be4da36-be92-4b3a-9d27-e2dfff81c8ff)

It is proposed to build the tree structure in the Browser (corresponding to the "menus" in the plugin) under a single LMFP entry:

![image](https://github.com/user-attachments/assets/894e3624-0e6d-40fc-aad7-ba011cfa6ca5)

But I suggest having one entry for each project and subfolders with groups and layer.

This should look like this:

![image](https://github.com/user-attachments/assets/0f7b05b6-52ae-4688-9b8a-dc0405e786c7)

A PR is on the way. 

### Additional context

This feature is similar to what the IDG plugin does: https://github.com/geo2france/idg-qgis-plugin/.

This feature request is formulated from [Agences de l'Eau](https://www.lesagencesdeleau.fr/) and ported  by [Oslandia](https://oslandia.com).

**Comment by jmkerloch** [comment]
For better readability of PR I suggest we do this in several steps:

- always add project in QGIS browser (no option for project)
- refactor code for multiple layer add to be able to support `Add all` option in browser
- add option in project to define if it should be enable in browser

**Comment by jmkerloch** [comment]
We also need to discuss how we will implement merge option for QGIS browser.

**Comment by jmkerloch** [comment]
For `Add all` option we can't use an item in explorer because it won't be last since item are always sorted alphabetically.

I suggest we use a menu with an action.

**Comment by xcaeag** [comment]
Yes, I was wondering what you were going to propose. 
A context menu for layer groups?
It's a shame to lose the order defined in the project.

And you won't need to add the ‘separator’ elements starting with ‘-’ either.

**Comment by Guts** [comment]
As part of this development, we also aim to allow project's icon that will be used in the QGIS browser tree, similar to what the IDG plugin does.

![image](https://github.com/user-attachments/assets/e37c1df2-f61f-418f-b522-f894ca435c1e)

There are two options:

- Using a project variable `lmfp_icon`:
  
  ![image](https://github.com/user-attachments/assets/9c9e4b51-2c23-4e5c-8794-01a0fa43c68f)


- The approach used by the IDG plugin, with a link named `icon` of type `HTTPS` in the project metadata/links:

   
  ![image](https://github.com/user-attachments/assets/3bd6f1ce-86f8-4c2b-831e-de33ef780ad3)


The first one seems "better" to me since it does not interfere with project's metadata, while the second allows using a project designed for the IDG plugin.

I propose supporting both methods.

**Comment by Guts** [comment]
We should also support project's metadata/hyperlinks as IDG plugin does to ensure a similar behavior:

![image](https://github.com/user-attachments/assets/eaade44b-ebbe-488e-9ee8-98ff2fa6048a)

**Comment by Guts** [comment]
Implemented in #129
